# Generated by Django 5.2.1 on 2025-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='valor',
            field=models.CharField(default=4334, max_length=255),
            preserve_default=False,
        ),
    ]
