# Generated by Django 5.2.1 on 2025-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensores_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientes',
            name='sig',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
    ]
