# Generated by Django 5.2.1 on 2025-05-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ambientes_sig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='valor',
        ),
    ]
