# Generated by Django 5.2.1 on 2025-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sensores_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
