# Generated by Django 5.2.1 on 2025-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_historico_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Luminosidade', 'Luminosidade'), ('Umidade', 'Umidade'), ('contador', 'contador')], max_length=255),
        ),
    ]
