# Generated by Django 5.2.1 on 2025-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sensores_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('temperatura', 'temperatura'), ('luminosidade', 'luminosidade'), ('umidade', 'umidade'), ('contador', 'contador')], max_length=255),
        ),
    ]
